
#  {-------------------------------------------------------------------}
#  Copyright © 2024 MOHAMMAD WILDAN NURYULDA - MWN - nuryulda@gmail.com
#  Created Date [Sunday, 21 Januari 2024 - 02:30:00]
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  Licensed under the Apache License, Version 2.0 (the "License") at;
#  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#  http://www.apache.org/licenses/LICENSE-2.0
#  {-------------------------------------------------------------------}

version: '2'
services:
  BK731:
    image: confluentinc/cp-server:7.3.1
    container_name: BK731
    network_mode: "host"
    extra_hosts:
      - "example.co.id:127.0.0.1"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    volumes:
      - /etc/kafka/data/kafka-data:/var/lib/kafka/data
      - /etc/kafka/jaas:/etc/kafka/jaas
      - /etc/kafka/secrets:/etc/kafka/secrets
    environment:
      # ================================= BROKER =================================
      # -> general config
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: R1

      # -> zookeeper connection
      KAFKA_ZOOKEEPER_CONNECT: example.co.id:2181,example.co.id:2181,example.co.id:2181
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 120000
      KAFKA_ZOOKEEPER_SET_ACL: 'true'

      # -> zookeeper connection ssl
      #KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
      #KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'true'
      #KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/example.co.id.keystore.jks
      #KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: confluent
      #KAFKA_ZOOKEEPER_SSL_KEYSTORE_TYPE: PKCS12
      #KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/example.co.id.truststore.jks
      #KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: confluent
      #KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_TYPE: JKS

      # -> acl
      KAFKA_SUPER_USERS: User:ANONYMOUS;User:admin
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'

      # -> listeners broker
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_SSL:SASL_SSL
      KAFKA_LISTENERS: PLAINTEXT://example.co.id:9092,SSL://example.co.id:9093,SASL_SSL://example.co.id:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://example.co.id:9092,SSL://example.co.id:9093,SASL_SSL://example.co.id:9094

      # -> log
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      # -> ssl broker
      KAFKA_SSL_KEYSTORE_FILENAME: example.co.id.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: cert_creds
      KAFKA_SSL_TRUSTSTORE_FILENAME: example.co.id.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: cert_creds
      KAFKA_SSL_KEY_CREDENTIALS: cert_creds

      # -> metrics reporter
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: example.co.id:9093,example.co.id:9093,example.co.id:9093
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 3
      CONFLUENT_METRICS_ENABLE: 'true'

      # -> metrics reporter ssl
      CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SSL
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/example.co.id.truststore.jks
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_PASSWORD: confluent
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/example.co.id.keystore.jks
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_PASSWORD: confluent
      CONFLUENT_METRICS_REPORTER_SSL_KEY_PASSWORD: confluent

      # -> components partitions and impersonation broker
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 3

      # -> disable auto-enable telemetry
      KAFKA_CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: 'false'

      # -> disable self balancing
      KAFKA_CONFLUENT_BALANCER_ENABLE: 'false'

      # -> disable health plus
      CONFLUENT_TELEMETRY_ENABLED: 'false'

      # -> jmx port
      KAFKA_JMX_PORT: 9582

      # -> timezone
      TZ: Asia/Jakarta

      # -> other broker stuff
      CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      KAFKA_HEAP_OPTS: -Xms8G
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/jaas/broker_server_jaas.conf
                  -Dzookeeper.client.secure=true
                  -Dzookeeper.ssl.keyStore.location=/etc/kafka/secrets/example.co.id.keystore.jks
                  -Dzookeeper.ssl.keyStore.password=confluent
                  -Dzookeeper.ssl.trustStore.location=/etc/kafka/secrets/example.co.id.truststore.jks
                  -Dzookeeper.ssl.trustStore.password=confluent
